spring.application.name=instrumentos-service

server.port=8081

#Configuração temporária H2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./InstrumentosMusicaisDB
spring.datasource.username=sa
spring.datasource.password=password

spring.h2.console.enabled=true


#Configuração ORACLE
#spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.username=system
#spring.datasource.password=manager

#spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@172.18.106.88:1521:XE
#spring.datasource.username=ANDROID
#spring.datasource.password=ANDROID