-- Oracle 12 ou Superior
CREATE TABLE Instrumento (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    descricao VARCHAR2(100) NOT NULL,
    preco number(10,2) NOT NULL
);

INSERT INTO Instrumento (nome, tipo, descricao, preco) VALUES ('Violao Cordas', 'Violão', 'Violao Cordas', 500.5);
INSERT INTO Instrumento (nome, tipo, descricao, preco) VALUES ('Teclado Yamara', 'Teclado', 'Teclado Yamara', 900.0);
INSERT INTO Instrumento (nome, tipo, descricao, preco) VALUES ('Tecaldo Korn', 'Tecaldo', 'Tecaldo Korn', 1200.3);


CREATE TABLE Usuario (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    usuario VARCHAR2(50) NOT NULL,
    senha VARCHAR2(50) NOT NULL,
    server VARCHAR2(100),
    token VARCHAR2(100)
);

INSERT INTO Usuario (usuario, senha, server, token) VALUES ('maria', '123', '192.168.1.167', null);


